- pkg:composer/skpr/config@1.0.0-alpha1
- pkg:composer/skpr/config@2.0.0-alpha1
- pkg:composer/skpr/config@2.0.0-beta1
- pkg:composer/skpr/config@2.0.0-beta2
- pkg:composer/skpr/config@2.1.0
- pkg:composer/skpr/config@2.2.0
- pkg:composer/skpr/config@2.2.1
- pkg:composer/skpr/config@3.0.0
- pkg:composer/skpr/config@3.0.1
- pkg:composer/skpr/config@3.0.2
