- pkg:composer/k8s/core@1.0.0
- pkg:composer/k8s/core@1.0.1
- pkg:composer/k8s/core@1.0.2
- pkg:composer/k8s/core@1.0.3
- pkg:composer/k8s/core@1.1.0
- pkg:composer/k8s/core@1.2.0
- pkg:composer/k8s/core@1.3.0
