- pkg:composer/maleficarum/config@1.0
- pkg:composer/maleficarum/config@1.1
- pkg:composer/maleficarum/config@2.0.0
- pkg:composer/maleficarum/config@2.0.1
- pkg:composer/maleficarum/config@3.0.0
- pkg:composer/maleficarum/config@4.0.0
- pkg:composer/maleficarum/config@5.0.0
