- pkg:composer/vntrungld/prometheus-exporter@v0.0.1
- pkg:composer/vntrungld/prometheus-exporter@v0.0.2
- pkg:composer/vntrungld/prometheus-exporter@v1.0.0
- pkg:composer/vntrungld/prometheus-exporter@v1.1.0
- pkg:composer/vntrungld/prometheus-exporter@v1.1.1
- pkg:composer/vntrungld/prometheus-exporter@v1.1.2
