- pkg:composer/mobilistics-gmbh/prometheus-monitoring@0.0.1
- pkg:composer/mobilistics-gmbh/prometheus-monitoring@0.1.0
- pkg:composer/mobilistics-gmbh/prometheus-monitoring@0.1.1
- pkg:composer/mobilistics-gmbh/prometheus-monitoring@0.1.2
- pkg:composer/mobilistics-gmbh/prometheus-monitoring@0.1.3
- pkg:composer/mobilistics-gmbh/prometheus-monitoring@0.1.4
- pkg:composer/mobilistics-gmbh/prometheus-monitoring@0.1.5
- pkg:composer/mobilistics-gmbh/prometheus-monitoring@1.0.0
- pkg:composer/mobilistics-gmbh/prometheus-monitoring@1.1.0
- pkg:composer/mobilistics-gmbh/prometheus-monitoring@2.0.0
