- pkg:composer/simpl/config@2.0.0
- pkg:composer/simpl/config@v1.0
- pkg:composer/simpl/config@v1.0-alpha
- pkg:composer/simpl/config@v1.0.1
- pkg:composer/simpl/config@v1.0.2
- pkg:composer/simpl/config@v1.1.0
- pkg:composer/simpl/config@v1.1.1
