- pkg:composer/flavacaster/configs@v1.0.0
- pkg:composer/flavacaster/configs@v1.0.1
- pkg:composer/flavacaster/configs@v1.0.2
- pkg:composer/flavacaster/configs@v1.0.3
- pkg:composer/flavacaster/configs@v1.0.4
