- pkg:composer/lunr/config@0.10.0
- pkg:composer/lunr/config@0.10.1
- pkg:composer/lunr/config@0.11.0
- pkg:composer/lunr/config@0.12.0
- pkg:composer/lunr/config@0.7.0
- pkg:composer/lunr/config@0.7.1
- pkg:composer/lunr/config@0.7.2
- pkg:composer/lunr/config@0.8.0
- pkg:composer/lunr/config@0.8.1
- pkg:composer/lunr/config@0.9.0
