- pkg:composer/ijanki/prometheus-bundle@v0.9.0
- pkg:composer/ijanki/prometheus-bundle@v0.9.1
- pkg:composer/ijanki/prometheus-bundle@v0.9.2
- pkg:composer/ijanki/prometheus-bundle@v0.9.3
- pkg:composer/ijanki/prometheus-bundle@v0.9.4
